application: codefensive
version: theta
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /docs
  static_dir: docs

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: codefensive.app
